themes:
  - name: "nordic"
    colors:
      - "#ebcb8b"
      - "#efd47f"
      - "#d08770"
      - "#d79784"
      - "#fb616a"
      - "#c5727a"
      - "#b48ead"
      - "#be9db8"
      - "#8fbcbb"
      - "#9fc6c5"
      - "#5e81ac"
      - "#81a1c1"
      - "#d8dee9"
      - "#bbc3d4"
      - "#c0c8d8"
      - "#4c566a"
      - "#434c5e"
      - "#2b4252"
      - "#2e3440"
      - "#242933"
      - "#222630"
